version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: drfclientes_v1
    container_name: clientes_web
    depends_on:
      - db
    volumes:
      - .:/usr/app
    ports:
      - 8000:8000"
  db:
    image: postgres:latest
    container_name: clientes_db
    ports:
      - "5432:5432"